// What the app's service worker does beyond the precache (src/sw.ts wires these to its events): it
// shows a push as a notification, opens the app at the alert a tapped notification names, and
// takes over when the app asks it to (once the investor chose Reload). Each takes the worker's
// global scope as an argument, so specs run it against a stand-in, and names only what it uses
// of the scope and the event: the types hold under both the DOM and the WebWorker libraries.

/** The app's icon and its badge (a white silhouette), generated by scripts/generate-icons.ts. */
export const NOTIFICATION_ICON = '/icons/icon-192.png';
export const NOTIFICATION_BADGE = '/icons/badge-96.png';
/** A push that says nothing usable still shows something: the browser requires a notification. */
const UNTITLED = 'New alert';

/** A window of the app, as the worker sees it (a WindowClient). */
export interface AppWindow {
  navigate(url: string): Promise<AppWindow | null>;
  focus(): Promise<AppWindow>;
}

/** What the handlers use of the worker's global scope (`self` in src/sw.ts). */
export interface WorkerScope {
  readonly registration: {
    showNotification(title: string, options?: NotificationOptions): Promise<void>;
  };
  readonly clients: {
    matchAll(options: { type: 'window'; includeUncontrolled: true }): Promise<readonly AppWindow[]>;
    openWindow(url: string): Promise<unknown>;
  };
  skipWaiting(): Promise<void>;
}

/** An event the worker may keep running for (an ExtendableEvent). */
interface Lasting {
  waitUntil(promise: Promise<unknown>): void;
}

/** A PushEvent: its data is null when the push carries none. */
export interface PushLike extends Lasting {
  readonly data: { json(): unknown } | null;
}

/** A NotificationEvent of a tap on the notification. */
export interface NotificationClickLike extends Lasting {
  readonly notification: { close(): void; readonly data: unknown };
}

/** A message posted to the worker by a page of the app. */
export interface MessageLike {
  readonly data: unknown;
}

/** What the notification keeps of its push, for the tap. */
interface Carried {
  notificationId: string | null;
}

/** A non-empty string, else undefined. */
function text(value: unknown): string | undefined {
  return typeof value === 'string' && value.trim() !== '' ? value : undefined;
}

/**
 * The platform sends `{ notificationId, title }` and nothing else, so no amount reaches the lock
 * screen; anything else a push carries is left out. A payload that is not JSON names nothing.
 */
function readPush(data: PushLike['data']): { notificationId?: string; title?: string } {
  let payload: unknown;
  try {
    payload = data?.json();
  } catch {
    return {};
  }
  if (typeof payload !== 'object' || payload === null) return {};
  const { notificationId, title } = payload as Record<string, unknown>;
  const read: { notificationId?: string; title?: string } = {};
  const id = text(notificationId);
  if (id !== undefined) read.notificationId = id;
  const heading = text(title);
  if (heading !== undefined) read.title = heading;
  return read;
}

/** A push: its title as a notification with the app's icon and badge, tagged with its alert. */
export function onPush(scope: WorkerScope, event: PushLike): void {
  const { notificationId, title } = readPush(event.data);
  const carried: Carried = { notificationId: notificationId ?? null };
  const options: NotificationOptions = {
    icon: NOTIFICATION_ICON,
    badge: NOTIFICATION_BADGE,
    data: carried,
  };
  // The alert's id as the tag: the same alert pushed twice replaces its notification.
  if (notificationId !== undefined) options.tag = notificationId;
  event.waitUntil(scope.registration.showNotification(title ?? UNTITLED, options));
}

/**
 * A tap on a notification: it closes, and the app opens at the alert it names (the alerts list
 * when it names none), in the window already open, else in a new one.
 */
export function onNotificationClick(scope: WorkerScope, event: NotificationClickLike): void {
  event.notification.close();
  const id = text((event.notification.data as Partial<Carried> | null | undefined)?.notificationId);
  const url = id === undefined ? '/alerts' : `/alerts?open=${encodeURIComponent(id)}`;
  event.waitUntil(openApp(scope, url));
}

async function openApp(scope: WorkerScope, url: string): Promise<unknown> {
  const [open] = await scope.clients.matchAll({ type: 'window', includeUncontrolled: true });
  if (open !== undefined) {
    try {
      // The browser answers null when it cannot say where the window went: it is still open.
      const there = (await open.navigate(url)) ?? open;
      return await there.focus();
    } catch {
      // A window this worker does not control cannot be taken there: a new one opens instead.
    }
  }
  return scope.clients.openWindow(url);
}

/** A page asked the waiting worker to take over (UpdateToast's Reload, through workbox-window). */
export function onMessage(scope: WorkerScope, event: MessageLike): void {
  const { data } = event;
  if (
    typeof data === 'object' &&
    data !== null &&
    (data as { type?: unknown }).type === 'SKIP_WAITING'
  ) {
    void scope.skipWaiting();
  }
}
